# Generated by Django 5.1 on 2024-09-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('status', models.SmallIntegerField(default=1, null=True, verbose_name='Estado')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Cliente',
                'ordering': ['name'],
            },
        ),
    ]
