# Generated by Django 5.1 on 2024-11-29 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 29, 10, 22, 26, 295609, tzinfo=datetime.timezone.utc), verbose_name='Fecha de Publicación'),
        ),
    ]
