# Generated by Django 5.1 on 2024-09-10 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodosPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, null=True, verbose_name='Metodos Pago')),
                ('status', models.IntegerField(default=1, null=True)),
            ],
            options={
                'verbose_name': 'Metodos de Pago',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Venta_Fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Venta')),
                ('Venta_NroFact', models.IntegerField(blank=True, null=True, verbose_name='Numero de Boleta')),
                ('Venta_Total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('Venta_CliId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_venta', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Ventas',
                'ordering': ['Venta_Fecha'],
            },
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VD_Cantidad', models.IntegerField(default=0, verbose_name='Cajas')),
                ('VD_Precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('VD_VentasId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Ventas',
                'ordering': ['VD_VentasId'],
            },
        ),
        migrations.CreateModel(
            name='Ventas_MP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VentasMP_Fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pago')),
                ('VentasMP_Total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('VentasMP_MP_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.metodospago')),
                ('VentasMP_Ventas_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Amortizaciones',
            },
        ),
    ]
