# Generated by Django 5.1 on 2024-11-29 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-Venta_CliId'], 'verbose_name': 'Ventas'},
        ),
        migrations.AlterModelOptions(
            name='ventas_mp',
            options={'ordering': ['-VentasMP_Ventas_Id'], 'verbose_name': 'Amortizaciones'},
        ),
    ]
